// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndpobqdkcffjbvoinglm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kcG9icWRrY2ZmamJ2b2luZ2xtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNDA5NzMsImV4cCI6MjA2OTgxNjk3M30.mIHDrg3MFHgKRbhLIHSOwQ72V5pmLigsNtgKuJ89BpY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});